### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by SUPERN00Bthefirst** [itsbumble/lunar-alternatives-for-fabric#1]
There is a fork of iris [The-HyperZone/Iris](https://github.com/The-HyperZone/Iris)
and its associated sodium fork [The-HyperZone/sodium-fabric](https://github.com/The-HyperZone/sodium-fabric)

They currently seem to work quite well.
Additionally, this fork of iris contains a shader selection screen.

**Comment by itsbumble** [comment]
Ah yeah I'll be adding that soon
